# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UiFiles/controlSettings/autonomy.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_autonomy(object):
    def setupUi(self, autonomy):
        autonomy.setObjectName("autonomy")
        autonomy.resize(334, 346)
        self.verticalLayout = QtWidgets.QVBoxLayout(autonomy)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(autonomy)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.fps_lineEdit = QtWidgets.QLineEdit(autonomy)
        self.fps_lineEdit.setMaximumSize(QtCore.QSize(30, 16777215))
        self.fps_lineEdit.setStyleSheet("")
        self.fps_lineEdit.setReadOnly(True)
        self.fps_lineEdit.setObjectName("fps_lineEdit")
        self.horizontalLayout_2.addWidget(self.fps_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.stream = QtWidgets.QWidget(autonomy)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stream.sizePolicy().hasHeightForWidth())
        self.stream.setSizePolicy(sizePolicy)
        self.stream.setStyleSheet("")
        self.stream.setObjectName("stream")
        self.verticalLayout.addWidget(self.stream)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(autonomy)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit.sizePolicy().hasHeightForWidth())
        self.plainTextEdit.setSizePolicy(sizePolicy)
        self.plainTextEdit.setMinimumSize(QtCore.QSize(0, 100))
        self.plainTextEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.plainTextEdit.setStyleSheet("background-color: LightGray")
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout.addWidget(self.plainTextEdit)

        self.retranslateUi(autonomy)
        QtCore.QMetaObject.connectSlotsByName(autonomy)

    def retranslateUi(self, autonomy):
        _translate = QtCore.QCoreApplication.translate
        autonomy.setWindowTitle(_translate("autonomy", "Form"))
        self.label.setText(_translate("autonomy", "FPS:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    autonomy = QtWidgets.QWidget()
    ui = Ui_autonomy()
    ui.setupUi(autonomy)
    autonomy.show()
    sys.exit(app.exec_())
