# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UiFiles\boatData.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_boatData(object):
    def setupUi(self, boatData):
        boatData.setObjectName("boatData")
        boatData.resize(633, 407)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(boatData.sizePolicy().hasHeightForWidth())
        boatData.setSizePolicy(sizePolicy)
        boatData.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(boatData)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.container = QtWidgets.QFrame(boatData)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.container.sizePolicy().hasHeightForWidth())
        self.container.setSizePolicy(sizePolicy)
        self.container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.container.setObjectName("container")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.container)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_frame = QtWidgets.QFrame(self.container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_frame.sizePolicy().hasHeightForWidth())
        self.label_frame.setSizePolicy(sizePolicy)
        self.label_frame.setObjectName("label_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.label_frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.l_depth = QtWidgets.QLabel(self.label_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_depth.sizePolicy().hasHeightForWidth())
        self.l_depth.setSizePolicy(sizePolicy)
        self.l_depth.setMinimumSize(QtCore.QSize(0, 30))
        self.l_depth.setMaximumSize(QtCore.QSize(16777215, 50))
        self.l_depth.setObjectName("l_depth")
        self.verticalLayout.addWidget(self.l_depth)
        self.l_bat = QtWidgets.QLabel(self.label_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_bat.sizePolicy().hasHeightForWidth())
        self.l_bat.setSizePolicy(sizePolicy)
        self.l_bat.setMinimumSize(QtCore.QSize(0, 30))
        self.l_bat.setMaximumSize(QtCore.QSize(16777215, 50))
        self.l_bat.setObjectName("l_bat")
        self.verticalLayout.addWidget(self.l_bat)
        self.l_mode = QtWidgets.QLabel(self.label_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_mode.sizePolicy().hasHeightForWidth())
        self.l_mode.setSizePolicy(sizePolicy)
        self.l_mode.setMinimumSize(QtCore.QSize(0, 30))
        self.l_mode.setMaximumSize(QtCore.QSize(16777215, 50))
        self.l_mode.setObjectName("l_mode")
        self.verticalLayout.addWidget(self.l_mode)
        self.l_humidity = QtWidgets.QLabel(self.label_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_humidity.sizePolicy().hasHeightForWidth())
        self.l_humidity.setSizePolicy(sizePolicy)
        self.l_humidity.setMinimumSize(QtCore.QSize(0, 30))
        self.l_humidity.setMaximumSize(QtCore.QSize(16777215, 50))
        self.l_humidity.setObjectName("l_humidity")
        self.verticalLayout.addWidget(self.l_humidity)
        self.l_grasper = QtWidgets.QLabel(self.label_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_grasper.sizePolicy().hasHeightForWidth())
        self.l_grasper.setSizePolicy(sizePolicy)
        self.l_grasper.setMinimumSize(QtCore.QSize(0, 30))
        self.l_grasper.setMaximumSize(QtCore.QSize(16777215, 50))
        self.l_grasper.setObjectName("l_grasper")
        self.verticalLayout.addWidget(self.l_grasper)
        self.horizontalLayout.addWidget(self.label_frame)
        self.data_frame = QtWidgets.QFrame(self.container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_frame.sizePolicy().hasHeightForWidth())
        self.data_frame.setSizePolicy(sizePolicy)
        self.data_frame.setObjectName("data_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.data_frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.depth_data = QtWidgets.QLabel(self.data_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.depth_data.sizePolicy().hasHeightForWidth())
        self.depth_data.setSizePolicy(sizePolicy)
        self.depth_data.setMinimumSize(QtCore.QSize(0, 30))
        self.depth_data.setMaximumSize(QtCore.QSize(16777215, 50))
        self.depth_data.setObjectName("depth_data")
        self.verticalLayout_2.addWidget(self.depth_data)
        self.mode_data = QtWidgets.QLabel(self.data_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mode_data.sizePolicy().hasHeightForWidth())
        self.mode_data.setSizePolicy(sizePolicy)
        self.mode_data.setMinimumSize(QtCore.QSize(0, 30))
        self.mode_data.setMaximumSize(QtCore.QSize(16777215, 50))
        self.mode_data.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.mode_data.setFrameShadow(QtWidgets.QFrame.Plain)
        self.mode_data.setObjectName("mode_data")
        self.verticalLayout_2.addWidget(self.mode_data)
        self.bat_data = QtWidgets.QLabel(self.data_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bat_data.sizePolicy().hasHeightForWidth())
        self.bat_data.setSizePolicy(sizePolicy)
        self.bat_data.setMinimumSize(QtCore.QSize(0, 30))
        self.bat_data.setMaximumSize(QtCore.QSize(16777215, 50))
        self.bat_data.setObjectName("bat_data")
        self.verticalLayout_2.addWidget(self.bat_data)
        self.hum_data = QtWidgets.QLabel(self.data_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hum_data.sizePolicy().hasHeightForWidth())
        self.hum_data.setSizePolicy(sizePolicy)
        self.hum_data.setMinimumSize(QtCore.QSize(0, 30))
        self.hum_data.setMaximumSize(QtCore.QSize(16777215, 50))
        self.hum_data.setObjectName("hum_data")
        self.verticalLayout_2.addWidget(self.hum_data)
        self.grasper_data = QtWidgets.QLabel(self.data_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grasper_data.sizePolicy().hasHeightForWidth())
        self.grasper_data.setSizePolicy(sizePolicy)
        self.grasper_data.setMinimumSize(QtCore.QSize(0, 30))
        self.grasper_data.setMaximumSize(QtCore.QSize(16777215, 50))
        self.grasper_data.setObjectName("grasper_data")
        self.verticalLayout_2.addWidget(self.grasper_data)
        self.horizontalLayout.addWidget(self.data_frame)
        self.horizontalLayout_2.addWidget(self.container)

        self.retranslateUi(boatData)
        QtCore.QMetaObject.connectSlotsByName(boatData)

    def retranslateUi(self, boatData):
        _translate = QtCore.QCoreApplication.translate
        boatData.setWindowTitle(_translate("boatData", "Form"))
        self.l_depth.setText(_translate("boatData", "depth"))
        self.l_bat.setText(_translate("boatData", "bat"))
        self.l_mode.setText(_translate("boatData", "mode"))
        self.l_humidity.setText(_translate("boatData", "humidity"))
        self.l_grasper.setText(_translate("boatData", "grasper"))
        self.depth_data.setText(_translate("boatData", "depth_data"))
        self.mode_data.setText(_translate("boatData", "mode_data"))
        self.bat_data.setText(_translate("boatData", "bat_data"))
        self.hum_data.setText(_translate("boatData", "hum_data"))
        self.grasper_data.setText(_translate("boatData", "grasper_data"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    boatData = QtWidgets.QWidget()
    ui = Ui_boatData()
    ui.setupUi(boatData)
    boatData.show()
    sys.exit(app.exec_())
