# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UiFiles/controlSettings.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_controlSettings(object):
    def setupUi(self, controlSettings):
        controlSettings.setObjectName("controlSettings")
        controlSettings.resize(500, 623)
        controlSettings.setMinimumSize(QtCore.QSize(0, 0))
        controlSettings.setMaximumSize(QtCore.QSize(500, 16777215))
        self.gridLayout = QtWidgets.QGridLayout(controlSettings)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(controlSettings)
        self.widget.setMinimumSize(QtCore.QSize(0, 20))
        self.widget.setObjectName("widget")
        self.gridLayout.addWidget(self.widget, 3, 1, 1, 5)
        self.b_arm = QtWidgets.QPushButton(controlSettings)
        self.b_arm.setObjectName("b_arm")
        self.gridLayout.addWidget(self.b_arm, 0, 5, 1, 1)
        self.s_control = QtWidgets.QComboBox(controlSettings)
        self.s_control.setObjectName("s_control")
        self.gridLayout.addWidget(self.s_control, 0, 4, 1, 1)
        self.label_6 = QtWidgets.QLabel(controlSettings)
        self.label_6.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 3, 1, 1)
        self.label_14 = QtWidgets.QLabel(controlSettings)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 0, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(controlSettings)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.e_roll = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.e_roll.setMinimum(1.0)
        self.e_roll.setSingleStep(0.1)
        self.e_roll.setObjectName("e_roll")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.e_roll)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.e_pitch = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.e_pitch.setWrapping(False)
        self.e_pitch.setFrame(True)
        self.e_pitch.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.e_pitch.setSpecialValueText("")
        self.e_pitch.setProperty("showGroupSeparator", False)
        self.e_pitch.setPrefix("")
        self.e_pitch.setSuffix("")
        self.e_pitch.setMinimum(1.0)
        self.e_pitch.setSingleStep(0.1)
        self.e_pitch.setObjectName("e_pitch")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.e_pitch)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.e_yaw = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.e_yaw.setMinimum(1.0)
        self.e_yaw.setSingleStep(0.1)
        self.e_yaw.setObjectName("e_yaw")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.e_yaw)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.e_throttle = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.e_throttle.setMinimum(1.0)
        self.e_throttle.setSingleStep(0.1)
        self.e_throttle.setProperty("value", 1.0)
        self.e_throttle.setObjectName("e_throttle")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.e_throttle)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label)
        self.e_vertical = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.e_vertical.setMinimum(1.0)
        self.e_vertical.setSingleStep(0.1)
        self.e_vertical.setProperty("value", 1.0)
        self.e_vertical.setObjectName("e_vertical")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.e_vertical)
        self.gridLayout.addWidget(self.groupBox, 2, 1, 1, 3)
        self.groupBox_3 = QtWidgets.QGroupBox(controlSettings)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 50))
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.e_deadzone = QtWidgets.QLineEdit(self.groupBox_3)
        self.e_deadzone.setObjectName("e_deadzone")
        self.horizontalLayout.addWidget(self.e_deadzone)
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout.addWidget(self.label_13)
        self.l_interval = QtWidgets.QLineEdit(self.groupBox_3)
        self.l_interval.setObjectName("l_interval")
        self.horizontalLayout.addWidget(self.l_interval)
        self.gridLayout.addWidget(self.groupBox_3, 1, 1, 1, 5)
        self.groupBox_2 = QtWidgets.QGroupBox(controlSettings)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.l_yaw = QtWidgets.QLineEdit(self.groupBox_2)
        self.l_yaw.setObjectName("l_yaw")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.l_yaw)
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.l_vertical = QtWidgets.QLineEdit(self.groupBox_2)
        self.l_vertical.setObjectName("l_vertical")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.l_vertical)
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.l_throttle = QtWidgets.QLineEdit(self.groupBox_2)
        self.l_throttle.setObjectName("l_throttle")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.l_throttle)
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.l_roll = QtWidgets.QSpinBox(self.groupBox_2)
        self.l_roll.setPrefix("")
        self.l_roll.setProperty("value", 30)
        self.l_roll.setObjectName("l_roll")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.l_roll)
        self.l_pitch = QtWidgets.QSpinBox(self.groupBox_2)
        self.l_pitch.setProperty("value", 30)
        self.l_pitch.setObjectName("l_pitch")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.l_pitch)
        self.gridLayout.addWidget(self.groupBox_2, 2, 4, 1, 2)
        self.l_PIDInterval = QtWidgets.QLineEdit(controlSettings)
        self.l_PIDInterval.setMaximumSize(QtCore.QSize(70, 16777215))
        self.l_PIDInterval.setAlignment(QtCore.Qt.AlignCenter)
        self.l_PIDInterval.setObjectName("l_PIDInterval")
        self.gridLayout.addWidget(self.l_PIDInterval, 0, 2, 1, 1)

        self.retranslateUi(controlSettings)
        QtCore.QMetaObject.connectSlotsByName(controlSettings)

    def retranslateUi(self, controlSettings):
        _translate = QtCore.QCoreApplication.translate
        controlSettings.setWindowTitle(_translate("controlSettings", "Form"))
        self.b_arm.setText(_translate("controlSettings", "Arm"))
        self.label_6.setText(_translate("controlSettings", "Control method:"))
        self.label_14.setText(_translate("controlSettings", "PID interval:"))
        self.groupBox.setTitle(_translate("controlSettings", "Expo"))
        self.label_2.setText(_translate("controlSettings", "Roll"))
        self.label_4.setText(_translate("controlSettings", "Pitch"))
        self.label_3.setText(_translate("controlSettings", "Yaw"))
        self.label_5.setText(_translate("controlSettings", "Throttle"))
        self.label.setText(_translate("controlSettings", "Vertical"))
        self.groupBox_3.setTitle(_translate("controlSettings", "Pad specific"))
        self.label_7.setText(_translate("controlSettings", "Pad deadzone"))
        self.e_deadzone.setText(_translate("controlSettings", "2000"))
        self.label_13.setText(_translate("controlSettings", "Interval (ms)"))
        self.l_interval.setText(_translate("controlSettings", "40"))
        self.groupBox_2.setTitle(_translate("controlSettings", "Limits"))
        self.label_8.setText(_translate("controlSettings", "Roll angle"))
        self.label_9.setText(_translate("controlSettings", "Pitch angle"))
        self.l_yaw.setText(_translate("controlSettings", "200"))
        self.label_10.setText(_translate("controlSettings", "Yaw"))
        self.l_vertical.setText(_translate("controlSettings", "400"))
        self.label_11.setText(_translate("controlSettings", "Vertical"))
        self.l_throttle.setText(_translate("controlSettings", "400"))
        self.label_12.setText(_translate("controlSettings", "Throttle"))
        self.l_roll.setSuffix(_translate("controlSettings", "°"))
        self.l_pitch.setSuffix(_translate("controlSettings", "°"))
        self.l_PIDInterval.setText(_translate("controlSettings", "1000"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    controlSettings = QtWidgets.QWidget()
    ui = Ui_controlSettings()
    ui.setupUi(controlSettings)
    controlSettings.show()
    sys.exit(app.exec_())
