# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UiFiles/osdSettings.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_osdSettings(object):
    def setupUi(self, osdSettings):
        osdSettings.setObjectName("osdSettings")
        osdSettings.resize(180, 182)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(osdSettings.sizePolicy().hasHeightForWidth())
        osdSettings.setSizePolicy(sizePolicy)
        osdSettings.setMinimumSize(QtCore.QSize(100, 182))
        self.verticalLayout = QtWidgets.QVBoxLayout(osdSettings)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(osdSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 120, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        self.widget.setPalette(palette)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(-1, 9, -1, 9)
        self.gridLayout.setObjectName("gridLayout")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 8, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 7, 0, 1, 1)
        self.heading_active = QtWidgets.QRadioButton(self.widget)
        self.heading_active.setText("")
        self.heading_active.setChecked(True)
        self.heading_active.setAutoExclusive(False)
        self.heading_active.setObjectName("heading_active")
        self.gridLayout.addWidget(self.heading_active, 5, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.horizon_x = QtWidgets.QSpinBox(self.widget)
        self.horizon_x.setProperty("value", 50)
        self.horizon_x.setObjectName("horizon_x")
        self.gridLayout.addWidget(self.horizon_x, 1, 4, 1, 1)
        self.horizon_y = QtWidgets.QSpinBox(self.widget)
        self.horizon_y.setProperty("value", 50)
        self.horizon_y.setObjectName("horizon_y")
        self.gridLayout.addWidget(self.horizon_y, 1, 5, 1, 1)
        self.horizon_active = QtWidgets.QRadioButton(self.widget)
        self.horizon_active.setText("")
        self.horizon_active.setChecked(True)
        self.horizon_active.setAutoExclusive(False)
        self.horizon_active.setObjectName("horizon_active")
        self.gridLayout.addWidget(self.horizon_active, 1, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 4, 1, 1)
        self.heading_y = QtWidgets.QSpinBox(self.widget)
        self.heading_y.setProperty("value", 5)
        self.heading_y.setObjectName("heading_y")
        self.gridLayout.addWidget(self.heading_y, 5, 5, 1, 1)
        self.depth_x = QtWidgets.QSpinBox(self.widget)
        self.depth_x.setProperty("value", 60)
        self.depth_x.setObjectName("depth_x")
        self.gridLayout.addWidget(self.depth_x, 7, 4, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 5, 1, 1)
        self.heading_x = QtWidgets.QSpinBox(self.widget)
        self.heading_x.setProperty("value", 50)
        self.heading_x.setObjectName("heading_x")
        self.gridLayout.addWidget(self.heading_x, 5, 4, 1, 1)
        self.depth_active = QtWidgets.QRadioButton(self.widget)
        self.depth_active.setText("")
        self.depth_active.setChecked(True)
        self.depth_active.setAutoExclusive(False)
        self.depth_active.setObjectName("depth_active")
        self.gridLayout.addWidget(self.depth_active, 7, 3, 1, 1)
        self.depth_y = QtWidgets.QSpinBox(self.widget)
        self.depth_y.setProperty("value", 50)
        self.depth_y.setObjectName("depth_y")
        self.gridLayout.addWidget(self.depth_y, 7, 5, 1, 1)
        self.battery_active = QtWidgets.QRadioButton(self.widget)
        self.battery_active.setText("")
        self.battery_active.setChecked(True)
        self.battery_active.setAutoExclusive(False)
        self.battery_active.setObjectName("battery_active")
        self.gridLayout.addWidget(self.battery_active, 8, 3, 1, 1)
        self.battery_x = QtWidgets.QSpinBox(self.widget)
        self.battery_x.setObjectName("battery_x")
        self.gridLayout.addWidget(self.battery_x, 8, 4, 1, 1)
        self.battery_y = QtWidgets.QSpinBox(self.widget)
        self.battery_y.setObjectName("battery_y")
        self.gridLayout.addWidget(self.battery_y, 8, 5, 1, 1)
        self.verticalLayout.addWidget(self.widget)
        self.b_setFS = QtWidgets.QPushButton(osdSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_setFS.sizePolicy().hasHeightForWidth())
        self.b_setFS.setSizePolicy(sizePolicy)
        self.b_setFS.setObjectName("b_setFS")
        self.verticalLayout.addWidget(self.b_setFS)

        self.retranslateUi(osdSettings)
        QtCore.QMetaObject.connectSlotsByName(osdSettings)

    def retranslateUi(self, osdSettings):
        _translate = QtCore.QCoreApplication.translate
        osdSettings.setWindowTitle(_translate("osdSettings", "Form"))
        osdSettings.setStatusTip(_translate("osdSettings", "Stream is splitted in 100x100 grid"))
        self.label_6.setText(_translate("osdSettings", "Battery"))
        self.label_2.setText(_translate("osdSettings", "Depth"))
        self.label.setText(_translate("osdSettings", "Horizon"))
        self.label_3.setText(_translate("osdSettings", "Heading"))
        self.label_4.setText(_translate("osdSettings", "X"))
        self.label_5.setText(_translate("osdSettings", "Y"))
        self.b_setFS.setText(_translate("osdSettings", "Full Sreen"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    osdSettings = QtWidgets.QWidget()
    ui = Ui_osdSettings()
    ui.setupUi(osdSettings)
    osdSettings.show()
    sys.exit(app.exec_())
