# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UiFiles/pidSetup.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pidSetup(object):
    def setupUi(self, pidSetup):
        pidSetup.setObjectName("pidSetup")
        pidSetup.resize(680, 279)
        pidSetup.setMinimumSize(QtCore.QSize(680, 200))
        self.main_layout = QtWidgets.QVBoxLayout(pidSetup)
        self.main_layout.setObjectName("main_layout")
        self.roll_layout = QtWidgets.QHBoxLayout()
        self.roll_layout.setObjectName("roll_layout")
        self.roll_title = QtWidgets.QLabel(pidSetup)
        self.roll_title.setMinimumSize(QtCore.QSize(120, 0))
        self.roll_title.setMaximumSize(QtCore.QSize(120, 16777215))
        self.roll_title.setObjectName("roll_title")
        self.roll_layout.addWidget(self.roll_title)
        self.roll_kp_label = QtWidgets.QLabel(pidSetup)
        self.roll_kp_label.setMaximumSize(QtCore.QSize(30, 16777215))
        self.roll_kp_label.setObjectName("roll_kp_label")
        self.roll_layout.addWidget(self.roll_kp_label)
        self.roll_kp_edit = QtWidgets.QDoubleSpinBox(pidSetup)
        self.roll_kp_edit.setMinimum(-1000.0)
        self.roll_kp_edit.setMaximum(1000.0)
        self.roll_kp_edit.setSingleStep(0.5)
        self.roll_kp_edit.setObjectName("roll_kp_edit")
        self.roll_layout.addWidget(self.roll_kp_edit)
        self.roll_ki_label = QtWidgets.QLabel(pidSetup)
        self.roll_ki_label.setMaximumSize(QtCore.QSize(30, 16777215))
        self.roll_ki_label.setObjectName("roll_ki_label")
        self.roll_layout.addWidget(self.roll_ki_label)
        self.roll_ki_edit = QtWidgets.QDoubleSpinBox(pidSetup)
        self.roll_ki_edit.setMinimum(-1000.0)
        self.roll_ki_edit.setSingleStep(0.5)
        self.roll_ki_edit.setProperty("value", 0.0)
        self.roll_ki_edit.setObjectName("roll_ki_edit")
        self.roll_layout.addWidget(self.roll_ki_edit)
        self.roll_kd_label = QtWidgets.QLabel(pidSetup)
        self.roll_kd_label.setMaximumSize(QtCore.QSize(30, 16777215))
        self.roll_kd_label.setObjectName("roll_kd_label")
        self.roll_layout.addWidget(self.roll_kd_label)
        self.roll_kd_edit = QtWidgets.QDoubleSpinBox(pidSetup)
        self.roll_kd_edit.setMinimum(-1000.0)
        self.roll_kd_edit.setMaximum(1000.0)
        self.roll_kd_edit.setSingleStep(0.5)
        self.roll_kd_edit.setObjectName("roll_kd_edit")
        self.roll_layout.addWidget(self.roll_kd_edit)
        self.roll_set_btn = QtWidgets.QPushButton(pidSetup)
        self.roll_set_btn.setObjectName("roll_set_btn")
        self.roll_layout.addWidget(self.roll_set_btn)
        self.roll_restore_btn = QtWidgets.QPushButton(pidSetup)
        self.roll_restore_btn.setObjectName("roll_restore_btn")
        self.roll_layout.addWidget(self.roll_restore_btn)
        self.main_layout.addLayout(self.roll_layout)
        self.pitch_layout = QtWidgets.QHBoxLayout()
        self.pitch_layout.setObjectName("pitch_layout")
        self.pitch_title = QtWidgets.QLabel(pidSetup)
        self.pitch_title.setMinimumSize(QtCore.QSize(120, 0))
        self.pitch_title.setMaximumSize(QtCore.QSize(120, 16777215))
        self.pitch_title.setObjectName("pitch_title")
        self.pitch_layout.addWidget(self.pitch_title)
        self.pitch_kp_label = QtWidgets.QLabel(pidSetup)
        self.pitch_kp_label.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pitch_kp_label.setObjectName("pitch_kp_label")
        self.pitch_layout.addWidget(self.pitch_kp_label)
        self.pitch_kp_edit = QtWidgets.QDoubleSpinBox(pidSetup)
        self.pitch_kp_edit.setMinimum(-1000.0)
        self.pitch_kp_edit.setMaximum(1000.0)
        self.pitch_kp_edit.setSingleStep(0.5)
        self.pitch_kp_edit.setObjectName("pitch_kp_edit")
        self.pitch_layout.addWidget(self.pitch_kp_edit)
        self.pitch_ki_label = QtWidgets.QLabel(pidSetup)
        self.pitch_ki_label.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pitch_ki_label.setObjectName("pitch_ki_label")
        self.pitch_layout.addWidget(self.pitch_ki_label)
        self.pitch_ki_edit = QtWidgets.QDoubleSpinBox(pidSetup)
        self.pitch_ki_edit.setMinimum(-1000.0)
        self.pitch_ki_edit.setSingleStep(0.5)
        self.pitch_ki_edit.setProperty("value", 0.0)
        self.pitch_ki_edit.setObjectName("pitch_ki_edit")
        self.pitch_layout.addWidget(self.pitch_ki_edit)
        self.pitch_kd_label = QtWidgets.QLabel(pidSetup)
        self.pitch_kd_label.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pitch_kd_label.setObjectName("pitch_kd_label")
        self.pitch_layout.addWidget(self.pitch_kd_label)
        self.pitch_kd_edit = QtWidgets.QDoubleSpinBox(pidSetup)
        self.pitch_kd_edit.setMinimum(-1000.0)
        self.pitch_kd_edit.setMaximum(1000.0)
        self.pitch_kd_edit.setSingleStep(0.5)
        self.pitch_kd_edit.setObjectName("pitch_kd_edit")
        self.pitch_layout.addWidget(self.pitch_kd_edit)
        self.pitch_set_btn = QtWidgets.QPushButton(pidSetup)
        self.pitch_set_btn.setObjectName("pitch_set_btn")
        self.pitch_layout.addWidget(self.pitch_set_btn)
        self.pitch_restore_btn = QtWidgets.QPushButton(pidSetup)
        self.pitch_restore_btn.setObjectName("pitch_restore_btn")
        self.pitch_layout.addWidget(self.pitch_restore_btn)
        self.main_layout.addLayout(self.pitch_layout)
        self.yaw_layout = QtWidgets.QHBoxLayout()
        self.yaw_layout.setObjectName("yaw_layout")
        self.yaw_title = QtWidgets.QLabel(pidSetup)
        self.yaw_title.setMinimumSize(QtCore.QSize(120, 0))
        self.yaw_title.setMaximumSize(QtCore.QSize(120, 16777215))
        self.yaw_title.setObjectName("yaw_title")
        self.yaw_layout.addWidget(self.yaw_title)
        self.yaw_kp_label = QtWidgets.QLabel(pidSetup)
        self.yaw_kp_label.setMaximumSize(QtCore.QSize(30, 16777215))
        self.yaw_kp_label.setObjectName("yaw_kp_label")
        self.yaw_layout.addWidget(self.yaw_kp_label)
        self.yaw_kp_edit = QtWidgets.QDoubleSpinBox(pidSetup)
        self.yaw_kp_edit.setMinimum(-1000.0)
        self.yaw_kp_edit.setMaximum(1000.0)
        self.yaw_kp_edit.setSingleStep(0.5)
        self.yaw_kp_edit.setObjectName("yaw_kp_edit")
        self.yaw_layout.addWidget(self.yaw_kp_edit)
        self.yaw_ki_label = QtWidgets.QLabel(pidSetup)
        self.yaw_ki_label.setMaximumSize(QtCore.QSize(30, 16777215))
        self.yaw_ki_label.setObjectName("yaw_ki_label")
        self.yaw_layout.addWidget(self.yaw_ki_label)
        self.yaw_ki_edit = QtWidgets.QDoubleSpinBox(pidSetup)
        self.yaw_ki_edit.setMinimum(-1000.0)
        self.yaw_ki_edit.setSingleStep(0.5)
        self.yaw_ki_edit.setProperty("value", 0.0)
        self.yaw_ki_edit.setObjectName("yaw_ki_edit")
        self.yaw_layout.addWidget(self.yaw_ki_edit)
        self.yaw_kd_label = QtWidgets.QLabel(pidSetup)
        self.yaw_kd_label.setMaximumSize(QtCore.QSize(30, 16777215))
        self.yaw_kd_label.setObjectName("yaw_kd_label")
        self.yaw_layout.addWidget(self.yaw_kd_label)
        self.yaw_kd_edit = QtWidgets.QDoubleSpinBox(pidSetup)
        self.yaw_kd_edit.setMinimum(-1000.0)
        self.yaw_kd_edit.setMaximum(1000.0)
        self.yaw_kd_edit.setSingleStep(0.5)
        self.yaw_kd_edit.setObjectName("yaw_kd_edit")
        self.yaw_layout.addWidget(self.yaw_kd_edit)
        self.yaw_set_btn = QtWidgets.QPushButton(pidSetup)
        self.yaw_set_btn.setObjectName("yaw_set_btn")
        self.yaw_layout.addWidget(self.yaw_set_btn)
        self.yaw_restore_btn = QtWidgets.QPushButton(pidSetup)
        self.yaw_restore_btn.setObjectName("yaw_restore_btn")
        self.yaw_layout.addWidget(self.yaw_restore_btn)
        self.main_layout.addLayout(self.yaw_layout)
        self.roll_level_layout = QtWidgets.QHBoxLayout()
        self.roll_level_layout.setObjectName("roll_level_layout")
        self.label_4 = QtWidgets.QLabel(pidSetup)
        self.label_4.setMinimumSize(QtCore.QSize(120, 0))
        self.label_4.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_4.setObjectName("label_4")
        self.roll_level_layout.addWidget(self.label_4)
        self.label = QtWidgets.QLabel(pidSetup)
        self.label.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label.setObjectName("label")
        self.roll_level_layout.addWidget(self.label)
        self.roll_level_kp_edit = QtWidgets.QDoubleSpinBox(pidSetup)
        self.roll_level_kp_edit.setObjectName("roll_level_kp_edit")
        self.roll_level_layout.addWidget(self.roll_level_kp_edit)
        self.label_7 = QtWidgets.QLabel(pidSetup)
        self.label_7.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_7.setObjectName("label_7")
        self.roll_level_layout.addWidget(self.label_7)
        self.roll_level_ki_edit = QtWidgets.QDoubleSpinBox(pidSetup)
        self.roll_level_ki_edit.setObjectName("roll_level_ki_edit")
        self.roll_level_layout.addWidget(self.roll_level_ki_edit)
        self.label_8 = QtWidgets.QLabel(pidSetup)
        self.label_8.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_8.setObjectName("label_8")
        self.roll_level_layout.addWidget(self.label_8)
        self.roll_level_kd_edit = QtWidgets.QDoubleSpinBox(pidSetup)
        self.roll_level_kd_edit.setObjectName("roll_level_kd_edit")
        self.roll_level_layout.addWidget(self.roll_level_kd_edit)
        self.roll_level_set_btn = QtWidgets.QPushButton(pidSetup)
        self.roll_level_set_btn.setObjectName("roll_level_set_btn")
        self.roll_level_layout.addWidget(self.roll_level_set_btn)
        self.roll_level_restore_btn = QtWidgets.QPushButton(pidSetup)
        self.roll_level_restore_btn.setObjectName("roll_level_restore_btn")
        self.roll_level_layout.addWidget(self.roll_level_restore_btn)
        self.main_layout.addLayout(self.roll_level_layout)
        self.pitch_level_layout = QtWidgets.QHBoxLayout()
        self.pitch_level_layout.setObjectName("pitch_level_layout")
        self.label_5 = QtWidgets.QLabel(pidSetup)
        self.label_5.setMinimumSize(QtCore.QSize(120, 0))
        self.label_5.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_5.setObjectName("label_5")
        self.pitch_level_layout.addWidget(self.label_5)
        self.label_2 = QtWidgets.QLabel(pidSetup)
        self.label_2.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_2.setObjectName("label_2")
        self.pitch_level_layout.addWidget(self.label_2)
        self.pitch_level_kp_edit = QtWidgets.QDoubleSpinBox(pidSetup)
        self.pitch_level_kp_edit.setObjectName("pitch_level_kp_edit")
        self.pitch_level_layout.addWidget(self.pitch_level_kp_edit)
        self.label_10 = QtWidgets.QLabel(pidSetup)
        self.label_10.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_10.setObjectName("label_10")
        self.pitch_level_layout.addWidget(self.label_10)
        self.pitch_level_ki_edit = QtWidgets.QDoubleSpinBox(pidSetup)
        self.pitch_level_ki_edit.setObjectName("pitch_level_ki_edit")
        self.pitch_level_layout.addWidget(self.pitch_level_ki_edit)
        self.label_11 = QtWidgets.QLabel(pidSetup)
        self.label_11.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_11.setObjectName("label_11")
        self.pitch_level_layout.addWidget(self.label_11)
        self.pitch_level_kd_edit = QtWidgets.QDoubleSpinBox(pidSetup)
        self.pitch_level_kd_edit.setObjectName("pitch_level_kd_edit")
        self.pitch_level_layout.addWidget(self.pitch_level_kd_edit)
        self.pitch_level_set_btn = QtWidgets.QPushButton(pidSetup)
        self.pitch_level_set_btn.setObjectName("pitch_level_set_btn")
        self.pitch_level_layout.addWidget(self.pitch_level_set_btn)
        self.pitch_level_restore_btn = QtWidgets.QPushButton(pidSetup)
        self.pitch_level_restore_btn.setObjectName("pitch_level_restore_btn")
        self.pitch_level_layout.addWidget(self.pitch_level_restore_btn)
        self.main_layout.addLayout(self.pitch_level_layout)
        self.depth_layout = QtWidgets.QHBoxLayout()
        self.depth_layout.setObjectName("depth_layout")
        self.label_6 = QtWidgets.QLabel(pidSetup)
        self.label_6.setMinimumSize(QtCore.QSize(120, 0))
        self.label_6.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_6.setObjectName("label_6")
        self.depth_layout.addWidget(self.label_6)
        self.label_3 = QtWidgets.QLabel(pidSetup)
        self.label_3.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_3.setObjectName("label_3")
        self.depth_layout.addWidget(self.label_3)
        self.depth_kp_edit = QtWidgets.QDoubleSpinBox(pidSetup)
        self.depth_kp_edit.setObjectName("depth_kp_edit")
        self.depth_layout.addWidget(self.depth_kp_edit)
        self.label_9 = QtWidgets.QLabel(pidSetup)
        self.label_9.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_9.setObjectName("label_9")
        self.depth_layout.addWidget(self.label_9)
        self.depth_ki_edit = QtWidgets.QDoubleSpinBox(pidSetup)
        self.depth_ki_edit.setObjectName("depth_ki_edit")
        self.depth_layout.addWidget(self.depth_ki_edit)
        self.label_12 = QtWidgets.QLabel(pidSetup)
        self.label_12.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_12.setObjectName("label_12")
        self.depth_layout.addWidget(self.label_12)
        self.depth_kd_edit = QtWidgets.QDoubleSpinBox(pidSetup)
        self.depth_kd_edit.setObjectName("depth_kd_edit")
        self.depth_layout.addWidget(self.depth_kd_edit)
        self.depth_set_btn = QtWidgets.QPushButton(pidSetup)
        self.depth_set_btn.setObjectName("depth_set_btn")
        self.depth_layout.addWidget(self.depth_set_btn)
        self.depth_restore_btn = QtWidgets.QPushButton(pidSetup)
        self.depth_restore_btn.setObjectName("depth_restore_btn")
        self.depth_layout.addWidget(self.depth_restore_btn)
        self.main_layout.addLayout(self.depth_layout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.all_set_btn = QtWidgets.QPushButton(pidSetup)
        self.all_set_btn.setObjectName("all_set_btn")
        self.horizontalLayout_4.addWidget(self.all_set_btn)
        self.all_restore_btn = QtWidgets.QPushButton(pidSetup)
        self.all_restore_btn.setObjectName("all_restore_btn")
        self.horizontalLayout_4.addWidget(self.all_restore_btn)
        self.main_layout.addLayout(self.horizontalLayout_4)
        self.status = QtWidgets.QLabel(pidSetup)
        self.status.setEnabled(True)
        self.status.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.status.setText("")
        self.status.setObjectName("status")
        self.main_layout.addWidget(self.status)

        self.retranslateUi(pidSetup)
        QtCore.QMetaObject.connectSlotsByName(pidSetup)

    def retranslateUi(self, pidSetup):
        _translate = QtCore.QCoreApplication.translate
        pidSetup.setWindowTitle(_translate("pidSetup", "Form"))
        self.roll_title.setText(_translate("pidSetup", "Roll PID"))
        self.roll_kp_label.setText(_translate("pidSetup", "Kp:"))
        self.roll_ki_label.setText(_translate("pidSetup", "Ki:"))
        self.roll_kd_label.setText(_translate("pidSetup", "Kd:"))
        self.roll_set_btn.setText(_translate("pidSetup", "SET"))
        self.roll_restore_btn.setText(_translate("pidSetup", "RESTORE"))
        self.pitch_title.setText(_translate("pidSetup", "Pitch PID"))
        self.pitch_kp_label.setText(_translate("pidSetup", "Kp:"))
        self.pitch_ki_label.setText(_translate("pidSetup", "Ki:"))
        self.pitch_kd_label.setText(_translate("pidSetup", "Kd:"))
        self.pitch_set_btn.setText(_translate("pidSetup", "SET"))
        self.pitch_restore_btn.setText(_translate("pidSetup", "RESTORE"))
        self.yaw_title.setText(_translate("pidSetup", "Yaw PID"))
        self.yaw_kp_label.setText(_translate("pidSetup", "Kp:"))
        self.yaw_ki_label.setText(_translate("pidSetup", "Ki:"))
        self.yaw_kd_label.setText(_translate("pidSetup", "Kd:"))
        self.yaw_set_btn.setText(_translate("pidSetup", "SET"))
        self.yaw_restore_btn.setText(_translate("pidSetup", "RESTORE"))
        self.label_4.setText(_translate("pidSetup", "Roll level"))
        self.label.setText(_translate("pidSetup", "Kp:"))
        self.label_7.setText(_translate("pidSetup", "Ki:"))
        self.label_8.setText(_translate("pidSetup", "Kd:"))
        self.roll_level_set_btn.setText(_translate("pidSetup", "SET"))
        self.roll_level_restore_btn.setText(_translate("pidSetup", "RESTORE"))
        self.label_5.setText(_translate("pidSetup", "Pitch level"))
        self.label_2.setText(_translate("pidSetup", "Kp:"))
        self.label_10.setText(_translate("pidSetup", "Ki:"))
        self.label_11.setText(_translate("pidSetup", "Kd:"))
        self.pitch_level_set_btn.setText(_translate("pidSetup", "SET"))
        self.pitch_level_restore_btn.setText(_translate("pidSetup", "RESTORE"))
        self.label_6.setText(_translate("pidSetup", "Depth"))
        self.label_3.setText(_translate("pidSetup", "Kp:"))
        self.label_9.setText(_translate("pidSetup", "Ki:"))
        self.label_12.setText(_translate("pidSetup", "Kd:"))
        self.depth_set_btn.setText(_translate("pidSetup", "SET"))
        self.depth_restore_btn.setText(_translate("pidSetup", "RESTORE"))
        self.all_set_btn.setText(_translate("pidSetup", "SET ALL"))
        self.all_restore_btn.setText(_translate("pidSetup", "RESTORE ALL"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    pidSetup = QtWidgets.QWidget()
    ui = Ui_pidSetup()
    ui.setupUi(pidSetup)
    pidSetup.show()
    sys.exit(app.exec_())
