# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UiFiles/pidSetup.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pidSetup(object):
    def setupUi(self, pidSetup):
        pidSetup.setObjectName("pidSetup")
        pidSetup.resize(680, 213)
        pidSetup.setMinimumSize(QtCore.QSize(680, 200))
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(pidSetup)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.roll_box = QtWidgets.QGroupBox(pidSetup)
        self.roll_box.setObjectName("roll_box")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.roll_box)
        self.verticalLayout.setContentsMargins(-1, 1, 1, 1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.roll_kp_label = QtWidgets.QLabel(self.roll_box)
        self.roll_kp_label.setMinimumSize(QtCore.QSize(73, 0))
        self.roll_kp_label.setMaximumSize(QtCore.QSize(73, 16777215))
        self.roll_kp_label.setObjectName("roll_kp_label")
        self.horizontalLayout.addWidget(self.roll_kp_label)
        self.roll_kp_edit = QtWidgets.QDoubleSpinBox(self.roll_box)
        self.roll_kp_edit.setMinimum(-1000.0)
        self.roll_kp_edit.setMaximum(1000.0)
        self.roll_kp_edit.setSingleStep(0.5)
        self.roll_kp_edit.setObjectName("roll_kp_edit")
        self.horizontalLayout.addWidget(self.roll_kp_edit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.roll_ki_label = QtWidgets.QLabel(self.roll_box)
        self.roll_ki_label.setMinimumSize(QtCore.QSize(73, 0))
        self.roll_ki_label.setMaximumSize(QtCore.QSize(73, 16777215))
        self.roll_ki_label.setObjectName("roll_ki_label")
        self.horizontalLayout_2.addWidget(self.roll_ki_label)
        self.roll_ki_edit = QtWidgets.QDoubleSpinBox(self.roll_box)
        self.roll_ki_edit.setMinimum(-1000.0)
        self.roll_ki_edit.setSingleStep(0.5)
        self.roll_ki_edit.setProperty("value", 0.0)
        self.roll_ki_edit.setObjectName("roll_ki_edit")
        self.horizontalLayout_2.addWidget(self.roll_ki_edit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.roll_kd_label = QtWidgets.QLabel(self.roll_box)
        self.roll_kd_label.setMinimumSize(QtCore.QSize(73, 0))
        self.roll_kd_label.setMaximumSize(QtCore.QSize(73, 16777215))
        self.roll_kd_label.setObjectName("roll_kd_label")
        self.horizontalLayout_3.addWidget(self.roll_kd_label)
        self.roll_kd_edit = QtWidgets.QDoubleSpinBox(self.roll_box)
        self.roll_kd_edit.setMinimum(-1000.0)
        self.roll_kd_edit.setMaximum(1000.0)
        self.roll_kd_edit.setSingleStep(0.5)
        self.roll_kd_edit.setObjectName("roll_kd_edit")
        self.horizontalLayout_3.addWidget(self.roll_kd_edit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(self.roll_box)
        self.label.setMinimumSize(QtCore.QSize(73, 0))
        self.label.setMaximumSize(QtCore.QSize(73, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.roll_rate_edit = QtWidgets.QDoubleSpinBox(self.roll_box)
        self.roll_rate_edit.setObjectName("roll_rate_edit")
        self.horizontalLayout_5.addWidget(self.roll_rate_edit)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.roll_set_btn = QtWidgets.QPushButton(self.roll_box)
        self.roll_set_btn.setObjectName("roll_set_btn")
        self.horizontalLayout_6.addWidget(self.roll_set_btn)
        self.roll_restore_btn = QtWidgets.QPushButton(self.roll_box)
        self.roll_restore_btn.setObjectName("roll_restore_btn")
        self.horizontalLayout_6.addWidget(self.roll_restore_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_23.addWidget(self.roll_box)
        self.pitch_box = QtWidgets.QGroupBox(pidSetup)
        self.pitch_box.setObjectName("pitch_box")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.pitch_box)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pitch_kp_label = QtWidgets.QLabel(self.pitch_box)
        self.pitch_kp_label.setMinimumSize(QtCore.QSize(73, 0))
        self.pitch_kp_label.setMaximumSize(QtCore.QSize(73, 16777215))
        self.pitch_kp_label.setObjectName("pitch_kp_label")
        self.horizontalLayout_7.addWidget(self.pitch_kp_label)
        self.pitch_kp_edit = QtWidgets.QDoubleSpinBox(self.pitch_box)
        self.pitch_kp_edit.setMinimum(-1000.0)
        self.pitch_kp_edit.setMaximum(1000.0)
        self.pitch_kp_edit.setSingleStep(0.5)
        self.pitch_kp_edit.setObjectName("pitch_kp_edit")
        self.horizontalLayout_7.addWidget(self.pitch_kp_edit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pitch_ki_label = QtWidgets.QLabel(self.pitch_box)
        self.pitch_ki_label.setMinimumSize(QtCore.QSize(73, 0))
        self.pitch_ki_label.setMaximumSize(QtCore.QSize(73, 16777215))
        self.pitch_ki_label.setObjectName("pitch_ki_label")
        self.horizontalLayout_9.addWidget(self.pitch_ki_label)
        self.pitch_ki_edit = QtWidgets.QDoubleSpinBox(self.pitch_box)
        self.pitch_ki_edit.setMinimum(-1000.0)
        self.pitch_ki_edit.setSingleStep(0.5)
        self.pitch_ki_edit.setProperty("value", 0.0)
        self.pitch_ki_edit.setObjectName("pitch_ki_edit")
        self.horizontalLayout_9.addWidget(self.pitch_ki_edit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pitch_kd_label = QtWidgets.QLabel(self.pitch_box)
        self.pitch_kd_label.setMinimumSize(QtCore.QSize(73, 0))
        self.pitch_kd_label.setMaximumSize(QtCore.QSize(73, 16777215))
        self.pitch_kd_label.setObjectName("pitch_kd_label")
        self.horizontalLayout_8.addWidget(self.pitch_kd_label)
        self.pitch_kd_edit = QtWidgets.QDoubleSpinBox(self.pitch_box)
        self.pitch_kd_edit.setMinimum(-1000.0)
        self.pitch_kd_edit.setMaximum(1000.0)
        self.pitch_kd_edit.setSingleStep(0.5)
        self.pitch_kd_edit.setObjectName("pitch_kd_edit")
        self.horizontalLayout_8.addWidget(self.pitch_kd_edit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_2 = QtWidgets.QLabel(self.pitch_box)
        self.label_2.setMinimumSize(QtCore.QSize(73, 0))
        self.label_2.setMaximumSize(QtCore.QSize(73, 16777215))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_21.addWidget(self.label_2)
        self.pitch_rate_edit = QtWidgets.QDoubleSpinBox(self.pitch_box)
        self.pitch_rate_edit.setObjectName("pitch_rate_edit")
        self.horizontalLayout_21.addWidget(self.pitch_rate_edit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pitch_set_btn = QtWidgets.QPushButton(self.pitch_box)
        self.pitch_set_btn.setObjectName("pitch_set_btn")
        self.horizontalLayout_10.addWidget(self.pitch_set_btn)
        self.pitch_restore_btn = QtWidgets.QPushButton(self.pitch_box)
        self.pitch_restore_btn.setObjectName("pitch_restore_btn")
        self.horizontalLayout_10.addWidget(self.pitch_restore_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_23.addWidget(self.pitch_box)
        self.yaw_box = QtWidgets.QGroupBox(pidSetup)
        self.yaw_box.setObjectName("yaw_box")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.yaw_box)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.yaw_kp_label = QtWidgets.QLabel(self.yaw_box)
        self.yaw_kp_label.setMinimumSize(QtCore.QSize(73, 0))
        self.yaw_kp_label.setMaximumSize(QtCore.QSize(73, 16777215))
        self.yaw_kp_label.setObjectName("yaw_kp_label")
        self.horizontalLayout_11.addWidget(self.yaw_kp_label)
        self.yaw_kp_edit = QtWidgets.QDoubleSpinBox(self.yaw_box)
        self.yaw_kp_edit.setMinimum(-1000.0)
        self.yaw_kp_edit.setMaximum(1000.0)
        self.yaw_kp_edit.setSingleStep(0.5)
        self.yaw_kp_edit.setObjectName("yaw_kp_edit")
        self.horizontalLayout_11.addWidget(self.yaw_kp_edit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.yaw_ki_label = QtWidgets.QLabel(self.yaw_box)
        self.yaw_ki_label.setMinimumSize(QtCore.QSize(73, 0))
        self.yaw_ki_label.setMaximumSize(QtCore.QSize(73, 16777215))
        self.yaw_ki_label.setObjectName("yaw_ki_label")
        self.horizontalLayout_12.addWidget(self.yaw_ki_label)
        self.yaw_ki_edit = QtWidgets.QDoubleSpinBox(self.yaw_box)
        self.yaw_ki_edit.setMinimum(-1000.0)
        self.yaw_ki_edit.setSingleStep(0.5)
        self.yaw_ki_edit.setProperty("value", 0.0)
        self.yaw_ki_edit.setObjectName("yaw_ki_edit")
        self.horizontalLayout_12.addWidget(self.yaw_ki_edit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.yaw_kd_label = QtWidgets.QLabel(self.yaw_box)
        self.yaw_kd_label.setMinimumSize(QtCore.QSize(73, 0))
        self.yaw_kd_label.setMaximumSize(QtCore.QSize(73, 16777215))
        self.yaw_kd_label.setObjectName("yaw_kd_label")
        self.horizontalLayout_13.addWidget(self.yaw_kd_label)
        self.yaw_kd_edit = QtWidgets.QDoubleSpinBox(self.yaw_box)
        self.yaw_kd_edit.setMinimum(-1000.0)
        self.yaw_kd_edit.setMaximum(1000.0)
        self.yaw_kd_edit.setSingleStep(0.5)
        self.yaw_kd_edit.setObjectName("yaw_kd_edit")
        self.horizontalLayout_13.addWidget(self.yaw_kd_edit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_4 = QtWidgets.QLabel(self.yaw_box)
        self.label_4.setMinimumSize(QtCore.QSize(73, 0))
        self.label_4.setMaximumSize(QtCore.QSize(73, 16777215))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_19.addWidget(self.label_4)
        self.yaw_rate_edit = QtWidgets.QDoubleSpinBox(self.yaw_box)
        self.yaw_rate_edit.setObjectName("yaw_rate_edit")
        self.horizontalLayout_19.addWidget(self.yaw_rate_edit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.yaw_set_btn = QtWidgets.QPushButton(self.yaw_box)
        self.yaw_set_btn.setObjectName("yaw_set_btn")
        self.horizontalLayout_14.addWidget(self.yaw_set_btn)
        self.yaw_restore_btn = QtWidgets.QPushButton(self.yaw_box)
        self.yaw_restore_btn.setObjectName("yaw_restore_btn")
        self.horizontalLayout_14.addWidget(self.yaw_restore_btn)
        self.verticalLayout_3.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_23.addWidget(self.yaw_box)
        self.depth_box = QtWidgets.QGroupBox(pidSetup)
        self.depth_box.setObjectName("depth_box")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.depth_box)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_3 = QtWidgets.QLabel(self.depth_box)
        self.label_3.setMinimumSize(QtCore.QSize(73, 0))
        self.label_3.setMaximumSize(QtCore.QSize(73, 16777215))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_17.addWidget(self.label_3)
        self.depth_kp_edit = QtWidgets.QDoubleSpinBox(self.depth_box)
        self.depth_kp_edit.setObjectName("depth_kp_edit")
        self.horizontalLayout_17.addWidget(self.depth_kp_edit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_9 = QtWidgets.QLabel(self.depth_box)
        self.label_9.setMinimumSize(QtCore.QSize(73, 0))
        self.label_9.setMaximumSize(QtCore.QSize(73, 16777215))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_15.addWidget(self.label_9)
        self.depth_ki_edit = QtWidgets.QDoubleSpinBox(self.depth_box)
        self.depth_ki_edit.setObjectName("depth_ki_edit")
        self.horizontalLayout_15.addWidget(self.depth_ki_edit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_12 = QtWidgets.QLabel(self.depth_box)
        self.label_12.setMinimumSize(QtCore.QSize(73, 0))
        self.label_12.setMaximumSize(QtCore.QSize(73, 16777215))
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_16.addWidget(self.label_12)
        self.depth_kd_edit = QtWidgets.QDoubleSpinBox(self.depth_box)
        self.depth_kd_edit.setObjectName("depth_kd_edit")
        self.horizontalLayout_16.addWidget(self.depth_kd_edit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_5 = QtWidgets.QLabel(self.depth_box)
        self.label_5.setMinimumSize(QtCore.QSize(73, 0))
        self.label_5.setMaximumSize(QtCore.QSize(73, 16777215))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_20.addWidget(self.label_5)
        self.depth_rate_edit = QtWidgets.QDoubleSpinBox(self.depth_box)
        self.depth_rate_edit.setObjectName("depth_rate_edit")
        self.horizontalLayout_20.addWidget(self.depth_rate_edit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.depth_set_btn = QtWidgets.QPushButton(self.depth_box)
        self.depth_set_btn.setObjectName("depth_set_btn")
        self.horizontalLayout_18.addWidget(self.depth_set_btn)
        self.depth_restore_btn = QtWidgets.QPushButton(self.depth_box)
        self.depth_restore_btn.setObjectName("depth_restore_btn")
        self.horizontalLayout_18.addWidget(self.depth_restore_btn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_23.addWidget(self.depth_box)
        self.verticalLayout_5.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.all_set_btn = QtWidgets.QPushButton(pidSetup)
        self.all_set_btn.setObjectName("all_set_btn")
        self.horizontalLayout_4.addWidget(self.all_set_btn)
        self.all_restore_btn = QtWidgets.QPushButton(pidSetup)
        self.all_restore_btn.setObjectName("all_restore_btn")
        self.horizontalLayout_4.addWidget(self.all_restore_btn)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_22.addLayout(self.verticalLayout_5)

        self.retranslateUi(pidSetup)
        QtCore.QMetaObject.connectSlotsByName(pidSetup)

    def retranslateUi(self, pidSetup):
        _translate = QtCore.QCoreApplication.translate
        pidSetup.setWindowTitle(_translate("pidSetup", "Form"))
        self.roll_box.setTitle(_translate("pidSetup", "Roll"))
        self.roll_kp_label.setText(_translate("pidSetup", "Kp:"))
        self.roll_ki_label.setText(_translate("pidSetup", "Ki:"))
        self.roll_kd_label.setText(_translate("pidSetup", "Kd:"))
        self.label.setText(_translate("pidSetup", "Error to rate"))
        self.roll_set_btn.setText(_translate("pidSetup", "SET"))
        self.roll_restore_btn.setText(_translate("pidSetup", "RESTORE"))
        self.pitch_box.setTitle(_translate("pidSetup", "Pitch"))
        self.pitch_kp_label.setText(_translate("pidSetup", "Kp:"))
        self.pitch_ki_label.setText(_translate("pidSetup", "Ki:"))
        self.pitch_kd_label.setText(_translate("pidSetup", "Kd:"))
        self.label_2.setText(_translate("pidSetup", "Error to rate"))
        self.pitch_set_btn.setText(_translate("pidSetup", "SET"))
        self.pitch_restore_btn.setText(_translate("pidSetup", "RESTORE"))
        self.yaw_box.setTitle(_translate("pidSetup", "Yaw"))
        self.yaw_kp_label.setText(_translate("pidSetup", "Kp:"))
        self.yaw_ki_label.setText(_translate("pidSetup", "Ki:"))
        self.yaw_kd_label.setText(_translate("pidSetup", "Kd:"))
        self.label_4.setText(_translate("pidSetup", "Error to rate"))
        self.yaw_set_btn.setText(_translate("pidSetup", "SET"))
        self.yaw_restore_btn.setText(_translate("pidSetup", "RESTORE"))
        self.depth_box.setTitle(_translate("pidSetup", "Depth"))
        self.label_3.setText(_translate("pidSetup", "Kp:"))
        self.label_9.setText(_translate("pidSetup", "Ki:"))
        self.label_12.setText(_translate("pidSetup", "Kd:"))
        self.label_5.setText(_translate("pidSetup", "Error to rate"))
        self.depth_set_btn.setText(_translate("pidSetup", "SET"))
        self.depth_restore_btn.setText(_translate("pidSetup", "RESTORE"))
        self.all_set_btn.setText(_translate("pidSetup", "SET ALL"))
        self.all_restore_btn.setText(_translate("pidSetup", "RESTORE ALL"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    pidSetup = QtWidgets.QWidget()
    ui = Ui_pidSetup()
    ui.setupUi(pidSetup)
    pidSetup.show()
    sys.exit(app.exec_())
